FROM node:22-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

COPY . .

RUN npm install --force  

RUN npm run build

EXPOSE 8080

CMD ["npm", "start", "--", "--host", "0.0.0.0", "--port", "8080"]
